name: Keep Render APIs Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 15 minutes
  workflow_dispatch: # Allow manual run

jobs:
  ping-apis:
    runs-on: ubuntu-latest
    steps:
      - name: Ping multiple Render APIs
        run: |
          echo "Pinging Site 1"
          curl -s --retry 3 --retry-delay 5 https://prismapi2.onrender.com > /dev/null

          echo "Pinging Site 2"
          curl -s --retry 3 --retry-delay 5 https://ppmcdnbackup.onrender.com/count/getv > /dev/null
