name: Keep Render API Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 15 minutes
  workflow_dispatch: # Allow manual runs

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Render API
        run: |
          curl -s --retry 3 --retry-delay 5 https://prismapi2.onrender.com/user/login > /dev/null
